#pragma once
// Format: X(namespace_suffix, ClassName, "screen-name")

#define SCREEN_LIST                                                                         \
    X(screens, SequencerScreen, "sequencer")                                                \
    X(screens::window, SequenceScreen, "sequence")                                          \
    X(screens::window, TempoChangeScreen, "tempo-change")                                   \
    X(screens::window, CountMetronomeScreen, "count-metronome")                             \
    X(screens::window, EditMultipleScreen, "edit-multiple")                                 \
    X(screens::window, TransmitProgramChangesScreen, "transmit-program-changes")            \
    X(screens::window, TimingCorrectScreen, "timing-correct")                               \
    X(screens::window, TimeDisplayScreen, "time-display")                                   \
    X(screens::window, PasteEventScreen, "paste-event")                                     \
    X(screens::window, MultiRecordingSetupScreen, "multi-recording-setup")                  \
    X(screens::window, MidiOutputScreen, "midi-output")                                     \
    X(screens::window, MidiInputScreen, "midi-input")                                       \
    X(screens::window, LoopBarsScreen, "loop-bars-window")                                  \
    X(screens::window, InsertEventScreen, "insert-event")                                   \
    X(screens::window, EraseAllOffTracksScreen, "erase-all-off-tracks")                     \
    X(screens::window, ChangeTsigScreen, "change-tsig")                                     \
    X(screens::window, EditVelocityScreen, "edit-velocity")                                 \
    X(screens::window, EraseScreen, "erase")                                                \
    X(screens::window, ChangeBarsScreen, "change-bars")                                     \
    X(screens::window, ChangeBars2Screen, "change-bars-2")                                  \
    X(screens::window, TrackScreen, "track")                                                \
    X(screens::window, Assign16LevelsScreen, "assign-16-levels")                            \
    X(screens::dialog, MidiInputMonitorScreen, "midi-input-monitor")                        \
    X(screens::dialog, MidiOutputMonitorScreen, "midi-output-monitor")                      \
    X(screens::dialog, MetronomeSoundScreen, "metronome-sound")                             \
    X(screens::dialog, CopySequenceScreen, "copy-sequence")                                 \
    X(screens::dialog, CopyTrackScreen, "copy-track")                                       \
    X(screens::dialog, DeleteSequenceScreen, "delete-sequence")                             \
    X(screens::dialog, DeleteTrackScreen, "delete-track")                                   \
    X(screens::dialog, DeleteAllSequencesScreen, "delete-all-sequences")                    \
    X(screens::dialog, DeleteAllTracksScreen, "delete-all-tracks")                          \
    X(screens, NextSeqPadScreen, "next-seq-pad")                                            \
    X(screens, NextSeqScreen, "next-seq")                                                   \
    X(screens, SongScreen, "song")                                                          \
    X(screens, TrMuteScreen, "track-mute")                                                  \
    X(screens, StepEditorScreen, "step-editor")                                             \
    X(screens, EventsScreen, "events")                                                      \
    X(screens, BarsScreen, "bars")                                                          \
    X(screens, TrMoveScreen, "tr-move")                                                     \
    X(screens, UserScreen, "user")                                                          \
    X(screens, AssignScreen, "assign")                                                      \
    X(screens::window, StepTcScreen, "step-timing-correct")                                 \
    X(screens, OthersScreen, "others")                                                      \
    X(screens, PurgeScreen, "purge")                                                        \
    X(screens, DrumScreen, "drum")                                                          \
    X(screens, TrimScreen, "trim")                                                          \
    X(screens, LoopScreen, "loop")                                                          \
    X(screens, ZoneScreen, "zone")                                                          \
    X(screens::window, NumberOfZonesScreen, "number-of-zones")                              \
    X(screens, SndParamsScreen, "params")                                                   \
    X(screens, PgmParamsScreen, "program-params")                                           \
    X(screens, PgmAssignScreen, "program-assign")                                           \
    X(screens, SelectDrumScreen, "select-drum")                                             \
    X(screens, SampleScreen, "sample")                                                      \
    X(screens::window, SoundScreen, "sound")                                                \
    X(screens::dialog, ConvertSoundScreen, "convert-sound")                                 \
    X(screens::dialog, CopySoundScreen, "copy-sound")                                       \
    X(screens::dialog, DeleteSoundScreen, "delete-sound")                                   \
    X(screens::dialog, MonoToStereoScreen, "mono-to-stereo")                                \
    X(screens::dialog, ResampleScreen, "resample")                                          \
    X(screens::dialog, StereoToMonoScreen, "stereo-to-mono")                                \
    X(screens, MixerScreen, "mixer")                                                        \
    X(screens, MixerSetupScreen, "mixer-setup")                                             \
    X(screens, SelectMixerDrumScreen, "select-mixer-drum")                                  \
    X(screens, FxEditScreen, "fx-edit")                                                     \
    X(screens::window, StartFineScreen, "start-fine")                                       \
    X(screens::window, EndFineScreen, "end-fine")                                           \
    X(screens::window, LoopToFineScreen, "loop-to-fine")                                    \
    X(screens::window, LoopEndFineScreen, "loop-end-fine")                                  \
    X(screens::window, ZoneStartFineScreen, "zone-start-fine")                              \
    X(screens::window, ZoneEndFineScreen, "zone-end-fine")                                  \
    X(screens::window, ChannelSettingsScreen, "channel-settings")                           \
    X(screens::window, EditSoundScreen, "edit-sound")                                       \
    X(screens::window, AssignmentViewScreen, "assignment-view")                             \
    X(screens::window, AutoChromaticAssignmentScreen, "auto-chromatic-assignment")          \
    X(screens::window, CopyNoteParametersScreen, "copy-note-parameters")                    \
    X(screens::window, KeepOrRetryScreen, "keep-or-retry")                                  \
    X(screens::window, MuteAssignScreen, "mute-assign")                                     \
    X(screens::window, ProgramScreen, "program")                                            \
    X(screens::window, VelocityModulationScreen, "velocity-modulation")                     \
    X(screens::window, VeloEnvFilterScreen, "velo-env-filter")                              \
    X(screens::window, VeloPitchScreen, "velo-pitch")                                       \
    X(screens::window, InitPadAssignScreen, "init-pad-assign")                              \
    X(screens::dialog, CreateNewProgramScreen, "create-new-program")                        \
    X(screens::dialog, CopyProgramScreen, "copy-program")                                   \
    X(screens::dialog, DeleteAllProgramsScreen, "delete-all-programs")                      \
    X(screens::dialog, DeleteAllSoundScreen, "delete-all-sound")                            \
    X(screens::dialog, DeleteProgramScreen, "delete-program")                               \
    X(screens, LoadScreen, "load")                                                          \
    X(screens, FormatScreen, "format")                                                      \
    X(screens, SetupScreen, "setup")                                                        \
    X(screens, SaveScreen, "save")                                                          \
    X(screens::window, DirectoryScreen, "directory")                                        \
    X(screens::window, LoadAProgramScreen, "load-a-program")                                \
    X(screens::window, LoadASequenceScreen, "load-a-sequence")                              \
    X(screens::window, LoadASequenceFromAllScreen, "load-a-sequence-from-all")              \
    X(screens::window, LoadASoundScreen, "load-a-sound")                                    \
    X(screens::window, LoadApsFileScreen, "load-aps-file")                                  \
    X(screens::window, Mpc2000XlAllFileScreen, "mpc2000xl-all-file")                        \
    X(screens::window, SaveAProgramScreen, "save-a-program")                                \
    X(screens::window, SaveASequenceScreen, "save-a-sequence")                              \
    X(screens::window, SaveASoundScreen, "save-a-sound")                                    \
    X(screens::window, SaveAllFileScreen, "save-all-file")                                  \
    X(screens::window, SaveApsFileScreen, "save-aps-file")                                  \
    X(screens::window, TransposePermanentScreen, "transpose-permanent")                     \
    X(screens::dialog2, DeleteAllFilesScreen, "delete-all-files")                           \
    X(screens::dialog, DeleteFileScreen, "delete-file")                                     \
    X(screens::dialog, DeleteFolderScreen, "delete-folder")                                 \
    X(screens::window, CantFindFileScreen, "cant-find-file")                                \
    X(screens::dialog, FileExistsScreen, "file-exists")                                     \
    X(screens::window, NameScreen, "name")                                                  \
    X(screens, VmpcDisksScreen, "vmpc-disks")                                               \
    X(screens, VmpcSettingsScreen, "vmpc-settings")                                         \
    X(screens::window, VmpcDirectToDiskRecorderScreen, "vmpc-direct-to-disk-recorder")      \
    X(screens::dialog, VmpcRecordJamScreen, "vmpc-record-jam")                              \
    X(screens::window, VmpcRecordingFinishedScreen, "vmpc-recording-finished")              \
    X(screens::window, VmpcResetKeyboardScreen, "vmpc-reset-keyboard")                      \
    X(screens, VerScreen, "ver")                                                            \
    X(screens, InitScreen, "init")                                                          \
    X(screens, SecondSeqScreen, "second-seq")                                               \
    X(screens, TransScreen, "trans")                                                        \
    X(screens, PunchScreen, "punch")                                                        \
    X(screens, SyncScreen, "sync")                                                          \
    X(screens::dialog2, PopupScreen, "popup")                                               \
    X(screens::window, SoundMemoryScreen, "sound-memory")                                   \
    X(screens::window, SongWindow, "song-window")                                           \
    X(screens::dialog, VmpcFileInUseScreen, "vmpc-file-in-use")                             \
    X(screens::window, IgnoreTempoChangeScreen, "ignore-tempo-change")                      \
    X(screens::window, LoopSongScreen, "loop-song")                                         \
    X(screens::dialog, DeleteSongScreen, "delete-song")                                     \
    X(screens::dialog, DeleteAllSongScreen, "delete-all-song")                              \
    X(screens::dialog, CopySongScreen, "copy-song")                                         \
    X(screens, VmpcKeyboardScreen, "vmpc-keyboard")                                         \
    X(screens, VmpcMidiScreen, "vmpc-midi")                                                 \
    X(screens::window, VmpcDiscardMappingChangesScreen, "vmpc-discard-mapping-changes")     \
    X(screens, VmpcAutoSaveScreen, "vmpc-auto-save")                                        \
    X(screens, MidiSwScreen, "midi-sw")                                                     \
    X(screens::window, VmpcConvertAndLoadWavScreen, "vmpc-convert-and-load-wav")            \
    X(screens::window, StepEditOptionsScreen, "step-edit-options")                          \
    X(screens::window, VmpcMidiPresetsScreen, "vmpc-midi-presets")                          \
    X(screens::window, VmpcWarningSettingsIgnoredScreen, "vmpc-warning-settings-ignored")   \
    X(screens::window, VmpcKnownControllerDetectedScreen, "vmpc-known-controller-detected") \
    X(screens::window, VmpcContinuePreviousSessionScreen, "vmpc-continue-previous-session") \
    X(screens::window, ConvertSongToSeqScreen, "convert-song-to-seq")                       \
    X(screens::window, LocateScreen, "locate")
