#pragma once

#define SCREEN_LIST \
    X(SequencerScreen, "sequencer") \
    X(SequenceScreen, "sequence") \
    X(TempoChangeScreen, "tempo-change") \
    X(CountMetronomeScreen, "count-metronome") \
    X(EditMultipleScreen, "edit-multiple") \
    X(TransmitProgramChangesScreen, "transmit-program-changes") \
    X(TimingCorrectScreen, "timing-correct") \
    X(TimeDisplayScreen, "time-display") \
    X(PasteEventScreen, "paste-event") \
    X(MultiRecordingSetupScreen, "multi-recording-setup") \
    X(MidiOutputScreen, "midi-output") \
    X(MidiInputScreen, "midi-input") \
    X(LoopBarsScreen, "loop-bars-window") \
    X(InsertEventScreen, "insert-event") \
    X(EraseAllOffTracksScreen, "erase-all-off-tracks") \
    X(ChangeTsigScreen, "change-tsig") \
    X(EditVelocityScreen, "edit-velocity") \
    X(EraseScreen, "erase") \
    X(ChangeBarsScreen, "change-bars") \
    X(ChangeBars2Screen, "change-bars-2") \
    X(TrackScreen, "track") \
    X(Assign16LevelsScreen, "assign-16-levels") \
    X(MidiInputMonitorScreen, "midi-input-monitor") \
    X(MidiOutputMonitorScreen, "midi-output-monitor") \
    X(MetronomeSoundScreen, "metronome-sound") \
    X(CopySequenceScreen, "copy-sequence") \
    X(CopyTrackScreen, "copy-track") \
    X(DeleteSequenceScreen, "delete-sequence") \
    X(DeleteTrackScreen, "delete-track") \
    X(DeleteAllSequencesScreen, "delete-all-sequences") \
    X(DeleteAllTracksScreen, "delete-all-tracks") \
    X(NextSeqPadScreen, "next-seq-pad") \
    X(NextSeqScreen, "next-seq") \
    X(SongScreen, "song") \
    X(TrMuteScreen, "track-mute") \
    X(StepEditorScreen, "step-editor") \
    X(EventsScreen, "events") \
    X(BarsScreen, "bars") \
    X(TrMoveScreen, "tr-move") \
    X(UserScreen, "user") \
    X(AssignScreen, "assign") \
    X(StepTcScreen, "step-timing-correct") \
    X(OthersScreen, "others") \
    X(PurgeScreen, "purge") \
    X(DrumScreen, "drum") \
    X(TrimScreen, "trim") \
    X(LoopScreen, "loop") \
    X(ZoneScreen, "zone") \
    X(NumberOfZonesScreen, "number-of-zones") \
    X(SndParamsScreen, "params") \
    X(PgmParamsScreen, "program-params") \
    X(PgmAssignScreen, "program-assign") \
    X(SelectDrumScreen, "select-drum") \
    X(SampleScreen, "sample") \
    X(SoundScreen, "sound") \
    X(ConvertSoundScreen, "convert-sound") \
    X(CopySoundScreen, "copy-sound") \
    X(DeleteSoundScreen, "delete-sound") \
    X(MonoToStereoScreen, "mono-to-stereo") \
    X(ResampleScreen, "resample") \
    X(StereoToMonoScreen, "stereo-to-mono") \
    X(MixerScreen, "mixer") \
    X(MixerSetupScreen, "mixer-setup") \
    X(SelectMixerDrumScreen, "select-mixer-drum") \
    X(FxEditScreen, "fx-edit") \
    X(StartFineScreen, "start-fine") \
    X(EndFineScreen, "end-fine") \
    X(LoopToFineScreen, "loop-to-fine") \
    X(LoopEndFineScreen, "loop-end-fine") \
    X(ZoneStartFineScreen, "zone-start-fine") \
    X(ZoneEndFineScreen, "zone-end-fine") \
    X(ChannelSettingsScreen, "channel-settings") \
    X(EditSoundScreen, "edit-sound") \
    X(AssignmentViewScreen, "assignment-view") \
    X(AutoChromaticAssignmentScreen, "auto-chromatic-assignment") \
    X(CopyNoteParametersScreen, "copy-note-parameters") \
    X(KeepOrRetryScreen, "keep-or-retry") \
    X(MuteAssignScreen, "mute-assign") \
    X(ProgramScreen, "program") \
    X(VelocityModulationScreen, "velocity-modulation") \
    X(VeloEnvFilterScreen, "velo-env-filter") \
    X(VeloPitchScreen, "velo-pitch") \
    X(InitPadAssignScreen, "init-pad-assign") \
    X(CreateNewProgramScreen, "create-new-program") \
    X(CopyProgramScreen, "copy-program") \
    X(DeleteAllProgramsScreen, "delete-all-programs") \
    X(DeleteAllSoundScreen, "delete-all-sound") \
    X(DeleteProgramScreen, "delete-program") \
    X(LoadScreen, "load") \
    X(FormatScreen, "format") \
    X(SetupScreen, "setup") \
    X(SaveScreen, "save") \
    X(DirectoryScreen, "directory") \
    X(LoadAProgramScreen, "load-a-program") \
    X(LoadASequenceScreen, "load-a-sequence") \
    X(LoadASequenceFromAllScreen, "load-a-sequence-from-all") \
    X(LoadASoundScreen, "load-a-sound") \
    X(LoadApsFileScreen, "load-aps-file") \
    X(Mpc2000XlAllFileScreen, "mpc2000xl-all-file") \
    X(SaveAProgramScreen, "save-a-program") \
    X(SaveASequenceScreen, "save-a-sequence") \
    X(SaveASoundScreen, "save-a-sound") \
    X(SaveAllFileScreen, "save-all-file") \
    X(SaveApsFileScreen, "save-aps-file") \
    X(DeleteAllFilesScreen, "delete-all-files") \
    X(DeleteFileScreen, "delete-file") \
    X(DeleteFolderScreen, "delete-folder") \
    X(CantFindFileScreen, "cant-find-file") \
    X(FileExistsScreen, "file-exists") \
    X(NameScreen, "name") \
    X(VmpcDisksScreen, "vmpc-disks") \
    X(VmpcSettingsScreen, "vmpc-settings") \
    X(VmpcDirectToDiskRecorderScreen, "vmpc-direct-to-disk-recorder") \
    X(VmpcRecordJamScreen, "vmpc-record-jam") \
    X(VmpcRecordingFinishedScreen, "vmpc-recording-finished") \
    X(VerScreen, "ver") \
    X(InitScreen, "init") \
    X(SecondSeqScreen, "second-seq") \
    X(TransScreen, "trans") \
    X(TransposePermanentScreen, "transpose-permanent") \
    X(PunchScreen, "punch") \
    X(SyncScreen, "sync") \
    X(PopupScreen, "popup") \
    X(SoundMemoryScreen, "sound-memory") \
    X(SongWindow, "song-window") \
    X(VmpcFileInUseScreen, "vmpc-file-in-use") \
    X(IgnoreTempoChangeScreen, "ignore-tempo-change") \
    X(LoopSongScreen, "loop-song") \
    X(DeleteSongScreen, "delete-song") \
    X(DeleteAllSongScreen, "delete-all-song") \
    X(CopySongScreen, "copy-song") \
    X(VmpcKeyboardScreen, "vmpc-keyboard") \
    X(VmpcMidiScreen, "vmpc-midi") \
    X(VmpcResetKeyboardScreen, "vmpc-reset-keyboard") \
    X(VmpcDiscardMappingChangesScreen, "vmpc-discard-mapping-changes") \
    X(VmpcAutoSaveScreen, "vmpc-auto-save") \
    X(MidiSwScreen, "midi-sw") \
    X(VmpcConvertAndLoadWavScreen, "vmpc-convert-and-load-wav") \
    X(StepEditOptionsScreen, "step-edit-options") \
    X(VmpcMidiPresetsScreen, "vmpc-midi-presets") \
    X(VmpcWarningSettingsIgnoredScreen, "vmpc-warning-settings-ignored") \
    X(VmpcKnownControllerDetectedScreen, "vmpc-known-controller-detected") \
    X(VmpcContinuePreviousSessionScreen, "vmpc-continue-previous-session") \
    X(ConvertSongToSeqScreen, "convert-song-to-seq") \
    X(LocateScreen, "locate")
