#include "StateView.hpp"

#include "eventregistry/State.hpp"

using namespace mpc;
using namespace mpc::eventregistry;

bool StateView::isProgramPadPressed(
    const ProgramPadIndex idx,
    const std::shared_ptr<sampler::Program> &program) const
{
    for (auto &e : state->programPadEvents)
    {
        if (e->padIndex == idx && e->program == program)
        {
            return true;
        }
    }
    return false;
}

bool StateView::isProgramPadPressedBySource(const ProgramPadIndex idx,
                                            const Source src) const
{
    for (auto &e : state->programPadEvents)
    {
        if (e->padIndex == idx && e->source == src)
        {
            return true;
        }
    }
    return false;
}

VelocityOrPressure StateView::getPressedProgramPadAfterTouchOrVelocity(
    const ProgramPadIndex idx) const
{
    std::optional<VelocityOrPressure> result;

    for (const auto &e : state->programPadEvents)
    {
        if (e->source == Source::NoteRepeat)
        {
            continue;
        }

        if (e->padIndex == idx)
        {
            if (e->pressure)
            {
                result = *e->pressure;
            }
            else if (!result)
            {
                result = e->velocity;
            }
        }
    }

    if (result)
    {
        return *result;
    }

    throw std::invalid_argument(
        "This method should only be called for program pads that are "
        "pressed, and the presses shouldn't be generated by the note repeat "
        "feature.\n");
}

bool StateView::isProgramPadPressed(const ProgramPadIndex idx) const
{
    for (auto &e : state->programPadEvents)
    {
        if (e->padIndex == idx)
        {
            return true;
        }
    }
    return false;
}

ProgramPadPressEventPtr StateView::getMostRecentProgramPadPress(
    const ProgramPadIndex idx,
    const std::vector<Source> &sourcesToExclude) const
{
    ProgramPadPressEventPtr latest = nullptr;

    for (auto &e : state->programPadEvents)
    {
        if (e->padIndex != idx)
        {
            continue;
        }

        bool excluded = false;
        for (auto &s : sourcesToExclude)
        {
            if (e->source == s)
            {
                excluded = true;
                break;
            }
        }
        if (excluded)
        {
            continue;
        }

        if (!latest || e->pressTime > latest->pressTime)
        {
            latest = e;
        }
    }

    return latest;
}

NoteOnEventPtr StateView::retrievePlayNoteEvent(const NoteNumber note) const
{
    for (auto &e : state->noteEvents)
    {
        if (e->noteNumber == note)
        {
            return e;
        }
    }
    return nullptr;
}

std::shared_ptr<sequencer::NoteOnEvent>
StateView::retrieveRecordNoteEvent(const NoteNumber note) const
{
    for (const auto &e : state->noteEvents)
    {
        if (e->noteNumber == note && e->recordNoteEvent)
        {
            return *e->recordNoteEvent;
        }
    }
    return {};
}

PhysicalPadPressEventPtr
StateView::retrievePhysicalPadPressEvent(const PhysicalPadIndex idx) const
{
    for (const auto &e : state->physicalPadEvents)
    {
        if (e->padIndex == idx)
        {
            return e;
        }
    }
    return {};
}

NoteOnEventPtr StateView::retrieveNoteEvent(const NoteNumber note,
                                            const Source src) const
{
    for (const auto &e : state->noteEvents)
    {
        if (e->noteNumber == note && e->source == src)
        {
            return e;
        }
    }
    return {};
}

int StateView::getTotalPressedProgramPadCount() const
{
    return state->programPadEvents.size();
}

int StateView::getTotalNoteOnCount() const
{
    return state->noteEvents.size();
}
