#pragma once

#include "UIKeyConstants.h"

keys_element_t keys[] =
{ std::make_tuple("none", -1)
, std::make_tuple("escape", UIKeyConstants::UIKeyboardHIDUsageKeyboardEscape)
, std::make_tuple("f1", UIKeyConstants::UIKeyboardHIDUsageKeyboardF1)
, std::make_tuple("f2", UIKeyConstants::UIKeyboardHIDUsageKeyboardF2)
, std::make_tuple("f3", UIKeyConstants::UIKeyboardHIDUsageKeyboardF3)
, std::make_tuple("f4", UIKeyConstants::UIKeyboardHIDUsageKeyboardF4)
, std::make_tuple("f5", UIKeyConstants::UIKeyboardHIDUsageKeyboardF5)
, std::make_tuple("f6", UIKeyConstants::UIKeyboardHIDUsageKeyboardF6)
, std::make_tuple("f7", UIKeyConstants::UIKeyboardHIDUsageKeyboardF7)
, std::make_tuple("f8", UIKeyConstants::UIKeyboardHIDUsageKeyboardF8)
, std::make_tuple("f9", UIKeyConstants::UIKeyboardHIDUsageKeyboardF9)
, std::make_tuple("f10", UIKeyConstants::UIKeyboardHIDUsageKeyboardF10)
, std::make_tuple("f11", UIKeyConstants::UIKeyboardHIDUsageKeyboardF11)
, std::make_tuple("f12", UIKeyConstants::UIKeyboardHIDUsageKeyboardF12)
, std::make_tuple("f13", UIKeyConstants::UIKeyboardHIDUsageKeyboardF13)
, std::make_tuple("f14", UIKeyConstants::UIKeyboardHIDUsageKeyboardF14)
, std::make_tuple("f15", UIKeyConstants::UIKeyboardHIDUsageKeyboardF15)
, std::make_tuple("f16", UIKeyConstants::UIKeyboardHIDUsageKeyboardF16)
, std::make_tuple("f17", UIKeyConstants::UIKeyboardHIDUsageKeyboardF17)
, std::make_tuple("f18", UIKeyConstants::UIKeyboardHIDUsageKeyboardF18)
, std::make_tuple("f19", UIKeyConstants::UIKeyboardHIDUsageKeyboardF19)
, std::make_tuple("f20", UIKeyConstants::UIKeyboardHIDUsageKeyboardF20)
, std::make_tuple("f21", UIKeyConstants::UIKeyboardHIDUsageKeyboardF21)
, std::make_tuple("f22", UIKeyConstants::UIKeyboardHIDUsageKeyboardF22)
, std::make_tuple("f23", UIKeyConstants::UIKeyboardHIDUsageKeyboardF23)
, std::make_tuple("f24", UIKeyConstants::UIKeyboardHIDUsageKeyboardF24)
, std::make_tuple("zenkaku/hankaku", UIKeyConstants::UIKeyboardHIDUsageKeyboardZenkakuHankakuKanji)
, std::make_tuple("kanji", -1)
, std::make_tuple("tab", UIKeyConstants::UIKeyboardHIDUsageKeyboardTab)
, std::make_tuple("\t", -1)
, std::make_tuple("caps lock", -1)
, std::make_tuple("left shift", UIKeyConstants::UIKeyboardHIDUsageKeyboardLeftShift)
, std::make_tuple("right shift", UIKeyConstants::UIKeyboardHIDUsageKeyboardRightShift)
, std::make_tuple("shift", UIKeyConstants::UIKeyboardHIDUsageKeyboardLeftShift)
, std::make_tuple("left control", UIKeyConstants::UIKeyboardHIDUsageKeyboardLeftControl)
, std::make_tuple("right control", UIKeyConstants::UIKeyboardHIDUsageKeyboardRightControl)
, std::make_tuple("control", UIKeyConstants::UIKeyboardHIDUsageKeyboardLeftControl)
, std::make_tuple("left alternate", UIKeyConstants::UIKeyboardHIDUsageKeyboardLeftAlt)
, std::make_tuple("left option", UIKeyConstants::UIKeyboardHIDUsageKeyboardLeftAlt)
, std::make_tuple("right alternate", UIKeyConstants::UIKeyboardHIDUsageKeyboardRightAlt)
, std::make_tuple("right option", UIKeyConstants::UIKeyboardHIDUsageKeyboardRightAlt)
, std::make_tuple("alternate", UIKeyConstants::UIKeyboardHIDUsageKeyboardLeftAlt)
, std::make_tuple("option", UIKeyConstants::UIKeyboardHIDUsageKeyboardLeftAlt)
, std::make_tuple("left meta", -1)
, std::make_tuple("right meta", -8)
, std::make_tuple("meta", -7)
, std::make_tuple("muhenkan", -9)
, std::make_tuple("international5", -9)
, std::make_tuple("henkan", -10)
, std::make_tuple("international4", -10)
, std::make_tuple("katakana hiragana", -11)
, std::make_tuple("international2", -11)
, std::make_tuple("super", -1)
, std::make_tuple("windows", -1)
, std::make_tuple("command", -1)
, std::make_tuple("left windows", -1)
, std::make_tuple("left gui", -1)
, std::make_tuple("right windows", -1)
, std::make_tuple("right gui", -1)
, std::make_tuple("application", -37)
, std::make_tuple("menu", -12)
, std::make_tuple("backspace", UIKeyConstants::UIKeyboardHIDUsageKeyboardDeleteOrBackspace)
, std::make_tuple("enter", UIKeyConstants::UIKeyboardHIDUsageKeyboardReturnOrEnter)
, std::make_tuple("\n", UIKeyConstants::UIKeyboardHIDUsageKeyboardReturnOrEnter)
, std::make_tuple("space", UIKeyConstants::UIKeyboardHIDUsageKeyboardSpacebar)
, std::make_tuple(" ", UIKeyConstants::UIKeyboardHIDUsageKeyboardSpacebar)
, std::make_tuple("1", UIKeyConstants::UIKeyboardHIDUsageKeyboard1)
, std::make_tuple("2", UIKeyConstants::UIKeyboardHIDUsageKeyboard2)
, std::make_tuple("3", UIKeyConstants::UIKeyboardHIDUsageKeyboard3)
, std::make_tuple("4", UIKeyConstants::UIKeyboardHIDUsageKeyboard4)
, std::make_tuple("5", UIKeyConstants::UIKeyboardHIDUsageKeyboard5)
, std::make_tuple("6", UIKeyConstants::UIKeyboardHIDUsageKeyboard6)
, std::make_tuple("7", UIKeyConstants::UIKeyboardHIDUsageKeyboard7)
, std::make_tuple("8", UIKeyConstants::UIKeyboardHIDUsageKeyboard8)
, std::make_tuple("9", UIKeyConstants::UIKeyboardHIDUsageKeyboard9)
, std::make_tuple("0", UIKeyConstants::UIKeyboardHIDUsageKeyboard0)
, std::make_tuple("a", UIKeyConstants::UIKeyboardHIDUsageKeyboardA)
, std::make_tuple("b", UIKeyConstants::UIKeyboardHIDUsageKeyboardB)
, std::make_tuple("c", UIKeyConstants::UIKeyboardHIDUsageKeyboardC)
, std::make_tuple("d", UIKeyConstants::UIKeyboardHIDUsageKeyboardD)
, std::make_tuple("e", UIKeyConstants::UIKeyboardHIDUsageKeyboardE)
, std::make_tuple("f", UIKeyConstants::UIKeyboardHIDUsageKeyboardF)
, std::make_tuple("g", UIKeyConstants::UIKeyboardHIDUsageKeyboardG)
, std::make_tuple("h", UIKeyConstants::UIKeyboardHIDUsageKeyboardH)
, std::make_tuple("i", UIKeyConstants::UIKeyboardHIDUsageKeyboardI)
, std::make_tuple("j", UIKeyConstants::UIKeyboardHIDUsageKeyboardJ)
, std::make_tuple("k", UIKeyConstants::UIKeyboardHIDUsageKeyboardK)
, std::make_tuple("l", UIKeyConstants::UIKeyboardHIDUsageKeyboardL)
, std::make_tuple("m", UIKeyConstants::UIKeyboardHIDUsageKeyboardM)
, std::make_tuple("n", UIKeyConstants::UIKeyboardHIDUsageKeyboardN)
, std::make_tuple("o", UIKeyConstants::UIKeyboardHIDUsageKeyboardO)
, std::make_tuple("p", UIKeyConstants::UIKeyboardHIDUsageKeyboardP)
, std::make_tuple("q", UIKeyConstants::UIKeyboardHIDUsageKeyboardQ)
, std::make_tuple("r", UIKeyConstants::UIKeyboardHIDUsageKeyboardR)
, std::make_tuple("s", UIKeyConstants::UIKeyboardHIDUsageKeyboardS)
, std::make_tuple("t", UIKeyConstants::UIKeyboardHIDUsageKeyboardT)
, std::make_tuple("u", UIKeyConstants::UIKeyboardHIDUsageKeyboardU)
, std::make_tuple("v", UIKeyConstants::UIKeyboardHIDUsageKeyboardV)
, std::make_tuple("w", UIKeyConstants::UIKeyboardHIDUsageKeyboardW)
, std::make_tuple("x", UIKeyConstants::UIKeyboardHIDUsageKeyboardX)
, std::make_tuple("y", UIKeyConstants::UIKeyboardHIDUsageKeyboardY)
, std::make_tuple("z", UIKeyConstants::UIKeyboardHIDUsageKeyboardZ)
, std::make_tuple("minus", UIKeyConstants::UIKeyboardHIDUsageKeyboardHyphen)
, std::make_tuple("equals", UIKeyConstants::UIKeyboardHIDUsageKeyboardEqualSign)
, std::make_tuple("-", UIKeyConstants::UIKeyboardHIDUsageKeypadHyphen)
, std::make_tuple("hat", -1)
, std::make_tuple("^", -1)
, std::make_tuple("yen", -1)
, std::make_tuple("\\", -1)
, std::make_tuple("atmark", -1)
, std::make_tuple("@", -1)
, std::make_tuple("left square bracket", UIKeyConstants::UIKeyboardHIDUsageKeyboardOpenBracket)
, std::make_tuple("[", UIKeyConstants::UIKeyboardHIDUsageKeyboardOpenBracket)
, std::make_tuple("semicolon", UIKeyConstants::UIKeyboardHIDUsageKeyboardSemicolon)
, std::make_tuple(";", UIKeyConstants::UIKeyboardHIDUsageKeyboardSemicolon)
, std::make_tuple("quote", UIKeyConstants::UIKeyboardHIDUsageKeyboardQuote)
, std::make_tuple(":", -1)
, std::make_tuple("right square bracket", UIKeyConstants::UIKeyboardHIDUsageKeyboardCloseBracket)
, std::make_tuple("]", UIKeyConstants::UIKeyboardHIDUsageKeyboardCloseBracket)
, std::make_tuple("comma", UIKeyConstants::UIKeyboardHIDUsageKeyboardComma)
, std::make_tuple(",", UIKeyConstants::UIKeyboardHIDUsageKeyboardComma)
, std::make_tuple("dot", UIKeyConstants::UIKeyboardHIDUsageKeyboardPeriod)
, std::make_tuple(".", UIKeyConstants::UIKeyboardHIDUsageKeyboardPeriod)
, std::make_tuple("slash", UIKeyConstants::UIKeyboardHIDUsageKeyboardSlash)
, std::make_tuple("/", UIKeyConstants::UIKeyboardHIDUsageKeyboardSlash)
, std::make_tuple("backslash", UIKeyConstants::UIKeyboardHIDUsageKeyboardBackslash)
, std::make_tuple("\\", -UIKeyConstants::UIKeyboardHIDUsageKeyboardBackslash)
, std::make_tuple("print screen", -13)
, std::make_tuple("scroll lock", -14)
, std::make_tuple("pause", -15)
, std::make_tuple("insert", UIKeyConstants::UIKeyboardHIDUsageKeyboardInsert)
, std::make_tuple("delete", UIKeyConstants::UIKeyboardHIDUsageKeyboardDeleteForward)
, std::make_tuple("home", UIKeyConstants::UIKeyboardHIDUsageKeyboardHome)
, std::make_tuple("end", UIKeyConstants::UIKeyboardHIDUsageKeyboardEnd)
, std::make_tuple("page up", UIKeyConstants::UIKeyboardHIDUsageKeyboardPageUp)
, std::make_tuple("page down", UIKeyConstants::UIKeyboardHIDUsageKeyboardPageDown)
, std::make_tuple("up", UIKeyConstants::UIKeyboardHIDUsageKeyboardUpArrow)
, std::make_tuple("left", UIKeyConstants::UIKeyboardHIDUsageKeyboardLeftArrow)
, std::make_tuple("down", UIKeyConstants::UIKeyboardHIDUsageKeyboardDownArrow)
, std::make_tuple("right", UIKeyConstants::UIKeyboardHIDUsageKeyboardRightArrow)
, std::make_tuple("num lock", -18)
, std::make_tuple("num slash", -1)
, std::make_tuple("num asterisk", -1)
, std::make_tuple("num minus", -1)
, std::make_tuple("num plus", -1)
, std::make_tuple("num enter", -1)
, std::make_tuple("num 7", -1)
, std::make_tuple("num 8", -1)
, std::make_tuple("num 9", -1)
, std::make_tuple("num 4", -1)
, std::make_tuple("num 5", -1)
, std::make_tuple("num 6", -1)
, std::make_tuple("num 1", -1)
, std::make_tuple("num 2", -1)
, std::make_tuple("num 3", -1)
, std::make_tuple("num 0", -1)
, std::make_tuple("num comma", -1)
, std::make_tuple("num dot", -1)
, std::make_tuple("num equal", -1)
, std::make_tuple("num plusminus", -19)
, std::make_tuple("num left paren", -20)
, std::make_tuple("num right paren", -21)
, std::make_tuple("num left brace", -38)
, std::make_tuple("num right brace", -39)
, std::make_tuple("num tab", -40)
, std::make_tuple("num backspace", -41)
, std::make_tuple("num a", -42)
, std::make_tuple("num b", -43)
, std::make_tuple("num c", -44)
, std::make_tuple("num d", -45)
, std::make_tuple("num e", -46)
, std::make_tuple("num f", -47)
, std::make_tuple("num xor", -48)
, std::make_tuple("num ^", -49)
, std::make_tuple("num %", -50)
, std::make_tuple("num <", -51)
, std::make_tuple("num >", -52)
, std::make_tuple("num &", -53)
, std::make_tuple("num &&", -54)
, std::make_tuple("num |", -55)
, std::make_tuple("num ||", -56)
, std::make_tuple("num :", -57)
, std::make_tuple("num #", -58)
, std::make_tuple("num space", -59)
, std::make_tuple("num @", -60)
, std::make_tuple("num !", -61)
, std::make_tuple("num memory store", -62)
, std::make_tuple("num memory recall", -63)
, std::make_tuple("num memory clear", -64)
, std::make_tuple("num memory add", -65)
, std::make_tuple("num memory subtract", -66)
, std::make_tuple("num memory multiply", -67)
, std::make_tuple("num memory divide", -68)
, std::make_tuple("num clear", -69)
, std::make_tuple("num clear entry", -70)
, std::make_tuple("num binary", -71)
, std::make_tuple("num octal", -72)
, std::make_tuple("num decimal", -73)
, std::make_tuple("num hexadecimal", -74)
, std::make_tuple("mute", -1)
, std::make_tuple("volume down", -1)
, std::make_tuple("volume up", -1)
, std::make_tuple("power", -22)
, std::make_tuple("sleep", -23)
, std::make_tuple("wake up", -24)
, std::make_tuple("screen lock", -25)
, std::make_tuple("www", -26)
, std::make_tuple("mail", -27)
, std::make_tuple("play pause", -28)
, std::make_tuple("next song", -29)
, std::make_tuple("previous song", -30)
, std::make_tuple("wlan", -31)
, std::make_tuple("bluetooth", -32)
, std::make_tuple("brightness down", -33)
, std::make_tuple("brightness up", -34)
, std::make_tuple("display off", -35)
, std::make_tuple("function", -1)
, std::make_tuple("eisuu", 0x66)
, std::make_tuple("lang2", 0x66)
, std::make_tuple("kana kana", 0x68)
, std::make_tuple("lang1", 0x68)
, std::make_tuple("lang3", -75)
, std::make_tuple("lang4", -76)
, std::make_tuple("lang5", -77)
, std::make_tuple("lang6", -78)
, std::make_tuple("lang7", -79)
, std::make_tuple("lang8", -80)
, std::make_tuple("lang9", -81)
, std::make_tuple("international1", -82)
, std::make_tuple("international3", -83)
, std::make_tuple("international6", -84)
, std::make_tuple("international7", -85)
, std::make_tuple("international8", -86)
, std::make_tuple("international9", -87)
, std::make_tuple("alternate erase", -88)
, std::make_tuple("cancel", -89)
, std::make_tuple("clear", -90)
, std::make_tuple("prior", -91)
, std::make_tuple("return", -92)
, std::make_tuple("separator", -93)
, std::make_tuple("out", -94)
, std::make_tuple("oper", -95)
, std::make_tuple("clear/again", -96)
, std::make_tuple("exsel", -97)
, std::make_tuple("num 00", -98)
, std::make_tuple("num 000", -99)
, std::make_tuple("thousands separator", -100)
, std::make_tuple("decimal separator", -101)
, std::make_tuple("currency unit", -102)
, std::make_tuple("currency sub-unit", -103)
};
