#include "PerformanceStateView.hpp"

#include "performance/PerformanceState.hpp"

using namespace mpc;
using namespace mpc::performance;

PerformanceStateView::PerformanceStateView(
    const std::shared_ptr<const PerformanceState> s) noexcept
    : state(s)
{
}

bool PerformanceStateView::isProgramPadPressed(
    const ProgramPadIndex idx, const ProgramIndex programIndex) const
{
    for (auto &e : state->programPadEvents)
    {
        if (e.padIndex == idx && e.programIndex == programIndex)
        {
            return true;
        }
    }
    return false;
}

VelocityOrPressure
PerformanceStateView::getPressedProgramPadAfterTouchOrVelocity(
    const ProgramPadIndex idx) const
{
    VelocityOrPressure result;

    for (const auto &e : state->programPadEvents)
    {
        if (e.source == PerformanceEventSource::NoteRepeat)
        {
            continue;
        }

        if (e.padIndex == idx)
        {
            if (e.pressure != NoPressure)
            {
                result = e.pressure;
            }
            else if (result == NoVelocityOrPressure)
            {
                result = e.velocity;
            }
        }
    }

    if (result != NoVelocityOrPressure)
    {
        return result;
    }

    throw std::invalid_argument(
        "This method should only be called for program pads that are "
        "pressed, and the presses shouldn't be generated by the note repeat "
        "feature.\n");
}

bool PerformanceStateView::isProgramPadPressed(const ProgramPadIndex idx) const
{
    for (auto &e : state->programPadEvents)
    {
        if (e.padIndex == idx)
        {
            return true;
        }
    }
    return false;
}

std::optional<ProgramPadPressEvent>
PerformanceStateView::getMostRecentProgramPadPress(
    const ProgramPadIndex idx,
    const std::vector<PerformanceEventSource> &sourcesToExclude) const
{
    std::optional<ProgramPadPressEvent> latest = std::nullopt;

    for (auto &e : state->programPadEvents)
    {
        if (e.padIndex != idx)
        {
            continue;
        }

        bool excluded = false;
        for (auto &s : sourcesToExclude)
        {
            if (e.source == s)
            {
                excluded = true;
                break;
            }
        }
        if (excluded)
        {
            continue;
        }

        if (!latest || e.pressTimeMs > latest->pressTimeMs)
        {
            latest = e;
        }
    }

    return latest;
}

int PerformanceStateView::getTotalNoteOnCount() const
{
    return state->noteEvents.size();
}

Program PerformanceStateView::getProgram(const DrumBusIndex drumBusIndex) const
{
    return state->drums[drumBusIndex].program;
}

performance::Drum
PerformanceStateView::getDrum(const DrumBusIndex drumBusIndex) const
{
    return state->drums[drumBusIndex];
}
